// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type MyClient struct {
	ID           int32          `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	IsProject    string         `json:"is_project"`
	SelfCapture  string         `json:"self_capture"`
	ClientPrefix string         `json:"client_prefix"`
	ClientLogo   string         `json:"client_logo"`
	Address      sql.NullString `json:"address"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	City         sql.NullString `json:"city"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}
