// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (MyClient, error)
	GetClient(ctx context.Context, id int32) (MyClient, error)
	GetClientBySlug(ctx context.Context, slug string) (MyClient, error)
	ListClients(ctx context.Context) ([]MyClient, error)
}

var _ Querier = (*Queries)(nil)
