// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	GetClient(ctx context.Context, id int32) (MyClient, error)
}

var _ Querier = (*Queries)(nil)
